[platformio]
default_envs = nodemcuv2
src_dir = .

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
build_src_filter =
  +<main.cpp>
  +<GameEngine.cpp>
  +<InputHandler.cpp>
  +<MatrixDisplay.cpp>
  +<NetManager.cpp>
  +<Tetromino.cpp>
  -<iottetris/>
lib_deps =
  wayoda/LedControl@^1.0.6
  bblanchon/ArduinoJson@^6.21.5
